version: '3.8'

services:
  php-apache:
    hostname: mirea.dev
    container_name: apache-php
    build: apache-php
    restart: always
    volumes:
      - ./apache-php/src:/var/www/html-dynamic
      - ./apache-php/ports.conf:/etc/apache2/ports.conf
      - ./apache-php/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache-php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9003:9003"
  nginx:
    container_name: nginx
    build: nginx
    restart: always
    volumes:
      - ./nginx/src:/usr/share/nginx/html-static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:8082"
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - './db/init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - "3306:3306"
  redis:
    container_name: redis
    image: redis:alpine3.16
    restart: always
    ports:
      - "6379:6379"